<?php

/**
 * @file
 * Stanford Cache Helper
 *
 * The Stanford Cache Helper assists when the standard Drupal caching may be incomplete.
 */

/**
 * Implements hook_block_view_alter().
 */
function stanford_cache_helper_block_view_alter(&$data, $block) {

  // If the menu block has no content, it might be due to caching.
  $delta = 'stanford_jsa_layouts-1';
  if ($block->delta == $delta) {
    if (!isset($data['content'])) {
      watchdog('stanford_cache_helper',
        'Menu block %menu is missing content. Subject is: %subject',
        array('%menu' => $delta, '%subject'=>$data['subject']),
        WATCHDOG_DEBUG);
      $block = module_invoke('menu_block', 'block_view', $delta);
    }
  }
}

/**
 * Implements hook_page_alter(&$page).
 */
function stanford_cache_helper_page_alter(&$page) {

  // If the page doesn't have a sidebar and it is displaying a node, it might
  // need the cache cleared.
  //
  // This requires refreshing the page twice for the page to render properly.
  if (!isset($page['sidebar_first'])) {
    if (isset ($page['content']['system_main']['nodes'])) {
      $key = (key($page['content']['system_main']['nodes']));
      watchdog('stanford_cache_helper',
        'First sidebar is missing. Page is: node/%key',
        array('%key' => $key),
        WATCHDOG_DEBUG);
      drupal_flush_all_caches();
    }
  }
}
